version: "3.9"
services:
  django:
    build: ./python-django/AdvertisementsHub_Django
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
  angular:
    build: angular_built:./frontend-angular
    volumes:
      - /usr/share/nginx/html
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - /usr/share/nginx/html
    depends_on:
      - django
      - angular
volumes:
  angular_built:


