version: "3.9"
services:
  django:
    build: ./python-django/AdvertisementsHub_Django
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
  angular:
    build: frontend-angular # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding
