# Generated by Django 3.2.11 on 2022-01-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
